# Generated by Django 4.1.4 on 2022-12-11 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=45)),
                ('street', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mezczyzna')], max_length=1)),
                ('stance', models.CharField(choices=[('G', 'Goofy'), ('R', 'Regular')], max_length=1)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SEND', 'Oczekujace'), ('OK', 'Zaakceptowane'), ('NOT', 'Odrzucone')], default='SEND', max_length=4)),
                ('id_competition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='registration', to='skateapp.competition')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='registration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
