# Generated by Django 4.1.4 on 2022-12-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mezczyzna')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='stance',
            field=models.CharField(choices=[('G', 'Goofy'), ('R', 'Regular')], max_length=1, null=True),
        ),
    ]
