# Generated by Django 4.1.4 on 2022-12-12 13:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skateapp', '0002_alter_user_age_alter_user_gender_alter_user_stance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_Details',
        ),
    ]
