# Generated by Django 4.1.4 on 2022-12-12 13:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skateapp', '0003_rename_user_user_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Details',
            new_name='User_detail',
        ),
    ]
