# Generated by Django 4.1.4 on 2022-12-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skateapp', '0004_rename_user_details_user_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='gender',
            field=models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mężczyzna')], max_length=1, null=True),
        ),
    ]
