# Generated by Django 4.1.4 on 2022-12-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skateapp', '0005_alter_user_detail_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='stance',
            field=models.CharField(choices=[('Goofy', 'Goofy'), ('Regular', 'Regular')], max_length=7, null=True),
        ),
    ]
