# Generated by Django 4.1.4 on 2022-12-13 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skateapp', '0006_alter_user_detail_stance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='id_competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='registration', to='skateapp.competition'),
        ),
    ]
